# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      # src
      - id: flake8
        name: flake8-src
        additional_dependencies: [
            flake8-awesome,
            flake8-docstrings,
            flake8-quotes,
            flake8-simplify,
            flake8-use-fstring
        ]
        exclude: ^tests/
        args:
          - "--ignore=I900,W391"
      # tests
      - id: flake8
        name: flake8-tests
        additional_dependencies: [
            flake8-awesome,
            flake8-docstrings,
            flake8-quotes,
            flake8-simplify,
            flake8-use-fstring
        ]
        files: ^tests/
        args:
          - "--ignore=I900,S101,W391"

  # mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: e1ba0b6
    hooks:
     - id: mypy
