name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-linting.txt
    - name: Analysing the code with Flake8
      run: python -m flake8 --exclude=.venv,*Primitives.py,dreamcoder* --ignore=I900,S101,S301,S403,W391
